/**
 * Clean Professional Accident Detection Dashboard Controller
 */

document.addEventListener("DOMContentLoaded", () => {
  // Navigation
  const navItems = document.querySelectorAll(".nav-item");
  const pageViews = document.querySelectorAll(".page-view");
  const pageTitle = document.getElementById("pageTitle");
  const pageSubtitle = document.getElementById("pageSubtitle");

  const pageHeaders = {
    dashboard: {
      title: "Accident Detection Dashboard",
      subtitle: "Real-time road incident monitoring and automatic first-responder dispatch.",
    },
    analyze: {
      title: "Analyze CCTV Video",
      subtitle: "Upload a CCTV video to check for possible accidents.",
    },
    location: {
      title: "Current Detection Location",
      subtitle: "CCTV camera node geocoding and site coordinates.",
    },
    alerts: {
      title: "Emergency Alerts Log",
      subtitle: "Recent automated first-responder notifications generated by POST /emergency-alert.",
    },
    settings: {
      title: "System Settings & Information",
      subtitle: "Current architecture configuration and server health.",
    },
  };

  function switchPage(pageKey) {
    navItems.forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.page === pageKey);
    });

    pageViews.forEach((view) => {
      view.classList.toggle("active", view.id === `page-${pageKey}`);
    });

    if (pageHeaders[pageKey]) {
      pageTitle.textContent = pageHeaders[pageKey].title;
      pageSubtitle.textContent = pageHeaders[pageKey].subtitle;
    }
  }

  navItems.forEach((btn) => {
    btn.addEventListener("click", () => switchPage(btn.dataset.page));
  });

  document.getElementById("topbarAnalyzeBtn")?.addEventListener("click", () => switchPage("analyze"));
  document.getElementById("dashGoToAnalyzeBtn")?.addEventListener("click", () => switchPage("analyze"));

  // Health Monitoring
  const sidebarStatusDot = document.getElementById("sidebarStatusDot");
  const sidebarStatusText = document.getElementById("sidebarStatusText");
  const dashStatusDot = document.getElementById("dashStatusDot");
  const dashSystemText = document.getElementById("dashSystemText");
  const dashHealthStatus = document.getElementById("dashHealthStatus");
  const settingsHealthText = document.getElementById("settingsHealthText");

  async function checkHealth() {
    try {
      const res = await fetch("/health");
      if (res.ok) {
        sidebarStatusDot.className = "status-dot online";
        sidebarStatusText.textContent = "System Online";
        dashStatusDot.className = "status-indicator-dot online";
        dashSystemText.textContent = "Online";
        dashHealthStatus.textContent = "Responding (200 OK)";
        dashHealthStatus.className = "meta-value text-success";
        if (settingsHealthText) settingsHealthText.textContent = "Responding (200 OK)";
      } else {
        throw new Error(`HTTP ${res.status}`);
      }
    } catch (err) {
      sidebarStatusDot.className = "status-dot offline";
      sidebarStatusText.textContent = "Offline";
      dashStatusDot.className = "status-indicator-dot offline";
      dashSystemText.textContent = "Offline";
      dashHealthStatus.textContent = "Unreachable";
      dashHealthStatus.className = "meta-value text-danger";
      if (settingsHealthText) settingsHealthText.textContent = "Unreachable";
    }
  }

  checkHealth();
  setInterval(checkHealth, 20000);

  // Video Upload & Analysis Elements
  const videoFileInput = document.getElementById("videoFileInput");
  const chooseVideoBtn = document.getElementById("chooseVideoBtn");
  const selectedFilenameDisplay = document.getElementById("selectedFilenameDisplay");
  const useSampleVideoBtn = document.getElementById("useSampleVideoBtn");
  const quickSampleBtn = document.getElementById("quickSampleBtn");
  const startAnalyzeBtn = document.getElementById("startAnalyzeBtn");
  const processingState = document.getElementById("processingState");
  const analysisResultContainer = document.getElementById("analysisResultContainer");
  const resultSafeBox = document.getElementById("resultSafeBox");
  const resultDangerBox = document.getElementById("resultDangerBox");

  // Video Dual Players
  const originalVideoPlayer = document.getElementById("originalVideoPlayer");
  const originalVideoPlaceholder = document.getElementById("originalVideoPlaceholder");
  const processedVideoPlayer = document.getElementById("processedVideoPlayer");
  const processedVideoPlaceholder = document.getElementById("processedVideoPlaceholder");

  // Dashboard Summary Elements
  const dashAccidentBadge = document.getElementById("dashAccidentBadge");
  const dashAccidentNote = document.getElementById("dashAccidentNote");
  const dashAccidentTag = document.getElementById("dashAccidentTag");
  const dashLastVideo = document.getElementById("dashLastVideo");
  const dashLastFrames = document.getElementById("dashLastFrames");
  const dashLastConfidence = document.getElementById("dashLastConfidence");
  const dashPolice = document.getElementById("dashPolice");
  const dashAmbulance = document.getElementById("dashAmbulance");
  const dashAlertStatus = document.getElementById("dashAlertStatus");
  const dashAlertTag = document.getElementById("dashAlertTag");

  // 7 Required Analysis Result Metrics Elements
  const metricAccidentStatus = document.getElementById("metricAccidentStatus");
  const metricConfidenceScore = document.getElementById("metricConfidenceScore");
  const metricTotalFrames = document.getElementById("metricTotalFrames");
  const metricInvolvedIds = document.getElementById("metricInvolvedIds");
  const metricEvidencePath = document.getElementById("metricEvidencePath");
  const evidenceThumbContainer = document.getElementById("evidenceThumbContainer");
  const evidenceThumbImg = document.getElementById("evidenceThumbImg");
  const metricLocationCoords = document.getElementById("metricLocationCoords");
  const metricEmergencyAlertStatus = document.getElementById("metricEmergencyAlertStatus");
  const metricReasonsRow = document.getElementById("metricReasonsRow");
  const metricReasonsList = document.getElementById("metricReasonsList");

  // Alerts Table
  const alertsTableBody = document.getElementById("alertsTableBody");
  const testAlertBtn = document.getElementById("testAlertBtn");

  let selectedFile = null;

  function setSelectedFile(file) {
    selectedFile = file;
    if (file) {
      selectedFilenameDisplay.textContent = `${file.name} (${(file.size / (1024 * 1024)).toFixed(2)} MB)`;
      startAnalyzeBtn.disabled = false;

      // Show original video in original video player
      if (originalVideoPlayer) {
        originalVideoPlayer.src = URL.createObjectURL(file);
        originalVideoPlayer.style.display = "block";
        if (originalVideoPlaceholder) originalVideoPlaceholder.style.display = "none";
        originalVideoPlayer.load();
      }

      // Reset processed video player
      if (processedVideoPlayer) {
        processedVideoPlayer.pause();
        processedVideoPlayer.removeAttribute("src");
        processedVideoPlayer.style.display = "none";
        if (processedVideoPlaceholder) {
          processedVideoPlaceholder.style.display = "block";
          processedVideoPlaceholder.textContent = "Processed video will appear here after analysis";
        }
      }
    } else {
      selectedFilenameDisplay.textContent = "No video selected";
      startAnalyzeBtn.disabled = true;
      if (originalVideoPlayer) {
        originalVideoPlayer.style.display = "none";
        originalVideoPlayer.removeAttribute("src");
      }
      if (originalVideoPlaceholder) originalVideoPlaceholder.style.display = "block";
    }
  }

  chooseVideoBtn.addEventListener("click", () => videoFileInput.click());

  videoFileInput.addEventListener("change", (e) => {
    if (e.target.files && e.target.files[0]) {
      setSelectedFile(e.target.files[0]);
    }
  });

  async function loadSampleVideo() {
    try {
      selectedFilenameDisplay.textContent = "Loading test_tracking.mp4...";
      const res = await fetch("/ml-model/test_tracking.mp4");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const blob = await res.blob();
      const file = new File([blob], "test_tracking.mp4", { type: "video/mp4" });
      setSelectedFile(file);
      switchPage("analyze");
    } catch (err) {
      console.warn("Could not load sample directly via URL:", err);
      selectedFilenameDisplay.textContent = "test_tracking.mp4 (Sample)";
      startAnalyzeBtn.disabled = false;
      if (originalVideoPlayer) {
        originalVideoPlayer.src = "/ml-model/test_tracking.mp4";
        originalVideoPlayer.style.display = "block";
        if (originalVideoPlaceholder) originalVideoPlaceholder.style.display = "none";
        originalVideoPlayer.load();
      }
      switchPage("analyze");
    }
  }

  useSampleVideoBtn?.addEventListener("click", loadSampleVideo);
  quickSampleBtn?.addEventListener("click", loadSampleVideo);

  // Analysis Execution
  startAnalyzeBtn.addEventListener("click", async () => {
    if (!selectedFile) return;

    // Reset UI
    analysisResultContainer.style.display = "none";
    resultSafeBox.style.display = "none";
    resultDangerBox.style.display = "none";
    if (evidenceThumbContainer) evidenceThumbContainer.style.display = "none";

    startAnalyzeBtn.disabled = true;
    processingState.style.display = "flex";

    const formData = new FormData();
    formData.append("file", selectedFile);

    try {
      const response = await fetch("/analyze-video", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const errJson = await response.json().catch(() => ({ detail: "Server error" }));
        throw new Error(errJson.detail || `HTTP ${response.status}`);
      }

      const result = await response.json();
      handleAnalysisResult(result, selectedFile.name);
    } catch (err) {
      alert(`Video processing failed: ${err.message}`);
    } finally {
      processingState.style.display = "none";
      startAnalyzeBtn.disabled = false;
    }
  });

  function handleAnalysisResult(data, videoName = "Video Stream") {
    analysisResultContainer.style.display = "block";

    // Ensure original video is displayed
    if (originalVideoPlayer && !originalVideoPlayer.src && data.original_video_url) {
      originalVideoPlayer.src = data.original_video_url;
      originalVideoPlayer.style.display = "block";
      if (originalVideoPlaceholder) originalVideoPlaceholder.style.display = "none";
      originalVideoPlayer.load();
    }

    // Load and play processed / annotated video
    if (data.processed_video_url && processedVideoPlayer) {
      processedVideoPlayer.src = `${data.processed_video_url}?t=${Date.now()}`;
      processedVideoPlayer.style.display = "block";
      if (processedVideoPlaceholder) processedVideoPlaceholder.style.display = "none";
      processedVideoPlayer.load();
    }

    // Update Dashboard Card 3 (Last Analysis)
    if (dashLastVideo) dashLastVideo.textContent = videoName;
    if (dashLastFrames) dashLastFrames.textContent = `${data.frames_processed || 0} frames`;
    if (dashLastConfidence) {
      dashLastConfidence.textContent = data.confidence !== undefined ? `${(data.confidence * 100).toFixed(1)}%` : "0.0%";
    }

    // 1. Accident Status
    if (metricAccidentStatus) {
      if (data.accident_suspected) {
        metricAccidentStatus.textContent = "Accident Detected";
        metricAccidentStatus.className = "metric-txt font-bold text-danger";
      } else {
        metricAccidentStatus.textContent = "No Accident Detected (Safe)";
        metricAccidentStatus.className = "metric-txt font-bold text-success";
      }
    }

    // 2. Confidence
    const confPct = `${((data.confidence || 0.0) * 100).toFixed(1)}%`;
    if (metricConfidenceScore) {
      metricConfidenceScore.textContent = confPct;
    }

    // 3. Frames Processed
    if (metricTotalFrames) {
      metricTotalFrames.textContent = `${data.frames_processed || 0} frames`;
    }

    // 4. Involved Vehicle IDs
    const vehicleIds = (data.involved_track_ids && data.involved_track_ids.length > 0)
      ? data.involved_track_ids.map((id) => `Vehicle #${id}`).join(", ")
      : "None (Safe)";
    if (metricInvolvedIds) {
      metricInvolvedIds.textContent = vehicleIds;
    }

    // 5. Evidence
    if (data.evidence_path) {
      const filename = data.evidence_path.split(/[\\/]/).pop();
      if (metricEvidencePath) metricEvidencePath.textContent = filename;
      if (evidenceThumbImg) evidenceThumbImg.src = `/evidence/${filename}?t=${Date.now()}`;
      if (evidenceThumbContainer) evidenceThumbContainer.style.display = "block";
    } else {
      if (metricEvidencePath) metricEvidencePath.textContent = "None captured (Normal traffic)";
      if (evidenceThumbContainer) evidenceThumbContainer.style.display = "none";
    }

    // 6. Location
    if (metricLocationCoords) {
      metricLocationCoords.textContent = "13.0827° N, 80.2707° E (Anna Salai Highway, Chennai)";
    }

    // Verification Reasons
    if (data.reasons && data.reasons.length > 0) {
      if (metricReasonsList) {
        metricReasonsList.innerHTML = "";
        data.reasons.forEach((r) => {
          const li = document.createElement("li");
          li.textContent = r;
          metricReasonsList.appendChild(li);
        });
      }
      if (metricReasonsRow) metricReasonsRow.style.display = "block";
    } else {
      if (metricReasonsRow) metricReasonsRow.style.display = "none";
    }

    if (data.accident_suspected) {
      // ⚠ ACCIDENT DETECTED
      resultSafeBox.style.display = "none";
      resultDangerBox.style.display = "block";

      // 7. Emergency Alert Status
      if (metricEmergencyAlertStatus) {
        metricEmergencyAlertStatus.textContent = "Dispatched (Notified Police & Ambulance)";
        metricEmergencyAlertStatus.className = "metric-txt font-bold text-danger";
      }

      // Update Dashboard Card 2
      if (dashAccidentBadge) {
        dashAccidentBadge.textContent = "Accident Detected";
        dashAccidentBadge.className = "status-banner-badge badge-danger";
      }
      if (dashAccidentNote) {
        dashAccidentNote.textContent = `Collision verified at ${confPct} confidence. Emergency alert sent.`;
      }
      if (dashAccidentTag) {
        dashAccidentTag.textContent = "Emergency";
        dashAccidentTag.className = "card-tag tag-danger";
      }

      // Trigger POST /emergency-alert
      triggerEmergencyAlert({
        accident_suspected: true,
        confidence: data.confidence || 0.9,
        involved_track_ids: data.involved_track_ids || [],
        reasons: data.reasons || [],
        evidence_path: data.evidence_path || null,
        latitude: 13.0827,
        longitude: 80.2707,
      });
    } else {
      // ✓ NO ACCIDENT DETECTED
      resultDangerBox.style.display = "none";
      resultSafeBox.style.display = "block";

      // 7. Emergency Alert Status
      if (metricEmergencyAlertStatus) {
        metricEmergencyAlertStatus.textContent = "Standby (No Alert Required)";
        metricEmergencyAlertStatus.className = "metric-txt font-bold text-success";
      }

      // Update Dashboard Card 2
      if (dashAccidentBadge) {
        dashAccidentBadge.textContent = "No Accident Detected";
        dashAccidentBadge.className = "status-banner-badge badge-normal";
      }
      if (dashAccidentNote) {
        dashAccidentNote.textContent = "All vehicles moving safely. No collision verified.";
      }
      if (dashAccidentTag) {
        dashAccidentTag.textContent = "Normal";
        dashAccidentTag.className = "card-tag tag-normal";
      }

      // Reset alert status on dashboard
      if (dashAlertTag) {
        dashAlertTag.textContent = "Standby";
        dashAlertTag.className = "card-tag";
      }
      if (dashPolice) dashPolice.textContent = "Standby (000-POLICE)";
      if (dashAmbulance) dashAmbulance.textContent = "Standby (000-AMBULANCE)";
      if (dashAlertStatus) dashAlertStatus.textContent = "Normal / No Alert Sent";
    }
  }

  // Emergency Alert API Trigger
  async function triggerEmergencyAlert(eventPayload) {
    try {
      const response = await fetch("/emergency-alert", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(eventPayload),
      });

      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const data = await response.json();

      // Update Dashboard Card 5 (Emergency Alert)
      dashAlertTag.textContent = "Alert Dispatched";
      dashAlertTag.className = "card-tag tag-danger";
      dashPolice.textContent = "Notified: Mock Police (000-POLICE)";
      dashAmbulance.textContent = "Notified: Mock Ambulance (000-AMBULANCE)";
      dashAlertStatus.textContent = `Delivered (Event ID: ${data.event_id?.slice(0, 8)}...)`;

      // Update Result section badge
      if (metricEmergencyAlertStatus) {
        metricEmergencyAlertStatus.textContent = `Dispatched (${data.status} to ${data.number_of_recipients} units)`;
      }

      // Add to Alerts Page Table
      addAlertToTable({
        time: new Date().toLocaleTimeString(),
        police: "Mock Police Station (000-POLICE)",
        ambulance: "Mock Ambulance Unit (000-AMBULANCE)",
        status: data.status || "mock_delivered",
        location: `${data.latitude ?? 13.0827}, ${data.longitude ?? 80.2707}`,
        eventId: data.event_id || "evt-mock",
      });
    } catch (err) {
      console.error("Failed to send emergency alert:", err);
      dashAlertStatus.textContent = "Alert Dispatch Error";
    }
  }

  function addAlertToTable(alert) {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${alert.time}</td>
      <td>${alert.police}</td>
      <td>${alert.ambulance}</td>
      <td><span class="table-badge badge-delivered">${alert.status}</span></td>
      <td>${alert.location}</td>
      <td><code>${alert.eventId.slice(0, 12)}...</code></td>
    `;
    alertsTableBody.insertBefore(tr, alertsTableBody.firstChild);
  }

  // Manual Test Alert Button (on Alerts page)
  testAlertBtn?.addEventListener("click", () => {
    triggerEmergencyAlert({
      accident_suspected: true,
      confidence: 0.95,
      involved_track_ids: [1, 4],
      reasons: ["Test alert triggered from dashboard"],
      latitude: 13.0827,
      longitude: 80.2707,
    });
    alert("Test emergency alert dispatched successfully to Mock Police and Ambulance services.");
  });

  // Demo Simulation Button
  document.getElementById("simulateAccidentDemoBtn")?.addEventListener("click", () => {
    const mockData = {
      status: "completed",
      accident_suspected: true,
      confidence: 0.942,
      involved_track_ids: [2, 5],
      reasons: [
        "Bounding box intersection threshold exceeded (> 0.45 IoU)",
        "Sudden deceleration (-32.4 px/frame) verified across 4 consecutive frames"
      ],
      evidence_path: "ml-model/evidence/accident_sample_evidence.png",
      frames_processed: 142,
    };
    handleAnalysisResult(mockData, "traffic_incident_cam04.mp4");
  });
});
